/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myPanel;

import domain.DisplayData;
import domain.Donation;
import domain.Donor;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Shadhin
 */
public class BloodSearch extends javax.swing.JPanel {

    /**
     * Creates new form BloodSearch
     */
    public BloodSearch() {
        initComponents();
        bloodSearchCB.setSelectedIndex(0);
    }
    DefaultTableModel model;
    String bloodG;

    public void showDonor(String bloodG) {
        //model.setRowCount(0);
        try {
            model.setRowCount(0);
        } catch (Exception e) {
        }
        DisplayData dd = new DisplayData();
        ArrayList<Donation> blood = dd.getBloodList(bloodG);
        if (blood.isEmpty()) {
            //model.setRowCount(0);
            JOptionPane.showMessageDialog(null, "Sorry! "+bloodG+" blood not available right now");
        } else {
            model = (DefaultTableModel) bloodSearchT.getModel();
            Object[] row = new Object[10];
            for (int i = 0; i < blood.size(); i++) {
                row[0] = blood.get(i).getDonationId();
                row[1] = blood.get(i).getDonorId();
                row[2] = blood.get(i).getdName();
                row[3] = blood.get(i).getdSex();
                row[4] = blood.get(i).getdBloodG();
                row[5] = blood.get(i).getdMobileN();
                row[6] = blood.get(i).getdEmail();
                row[7] = blood.get(i).getdAddress();
                row[8] = blood.get(i).getdAlternativeMN();
                row[9] = blood.get(i).getDonationDate();
                model.addRow(row);
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bSearchB = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        bloodSearchT = new javax.swing.JTable();
        bloodSearchCB = new javax.swing.JComboBox<>();

        setMaximumSize(new java.awt.Dimension(700, 503));
        setMinimumSize(new java.awt.Dimension(700, 503));
        setPreferredSize(new java.awt.Dimension(700, 503));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Blood Search");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Blood Group:");

        bSearchB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bSearchB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/searchButtonIcon.png"))); // NOI18N
        bSearchB.setText("Search");
        bSearchB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSearchBActionPerformed(evt);
            }
        });

        bloodSearchT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bloodSearchT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Donor Id", "Name", "Sex", "Blood Group", "Mobile Number", "Email", "Address", "Alternative Mobile Number", "Donation Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(bloodSearchT);

        bloodSearchCB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bloodSearchCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(73, 547, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(66, 66, 66)
                        .addComponent(bloodSearchCB, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bSearchB)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(bSearchB)
                    .addComponent(bloodSearchCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bSearchBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSearchBActionPerformed
        // TODO add your handling code here:
         bloodG = bloodSearchCB.getSelectedItem().toString();
        //model.setRowCount(0);
        showDonor(bloodG);
    }//GEN-LAST:event_bSearchBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bSearchB;
    private javax.swing.JComboBox<String> bloodSearchCB;
    private javax.swing.JTable bloodSearchT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
