/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myPanel;

import domain.DisplayData;
import domain.Donation;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Shadhin
 */
public class BloodBank extends javax.swing.JPanel {

    /**
     * Creates new form Inventory
     */
    DefaultTableModel model;

    public BloodBank() {
        initComponents();

    }

    public void showDonor() {
        try {
            model.setRowCount(0);
        } catch (Exception e) {
        }
        DisplayData dd = new DisplayData();
        ArrayList<Donation> blood = dd.getDonationList();
        model = (DefaultTableModel) bloodBankT.getModel();
        Object[] row = new Object[10];
        for (int i = 0; i < blood.size(); i++) {
            row[0] = blood.get(i).getDonationId();
            row[1] = blood.get(i).getDonorId();
            row[2] = blood.get(i).getdName();
            row[3] = blood.get(i).getdSex();
            row[4] = blood.get(i).getdBloodG();
            row[5] = blood.get(i).getdMobileN();
            row[6] = blood.get(i).getdEmail();
            row[7] = blood.get(i).getdAddress();
            row[8] = blood.get(i).getdAlternativeMN();
            row[9] = blood.get(i).getDonationDate();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bloodBankT = new javax.swing.JTable();

        setMaximumSize(new java.awt.Dimension(700, 503));
        setMinimumSize(new java.awt.Dimension(700, 503));
        setPreferredSize(new java.awt.Dimension(700, 503));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Blood Bank");

        bloodBankT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bloodBankT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Donor Id", "Name", "Sex", "Blood Group", "Mobile Number", "Email", "Address", "Alternative Mobile Number", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(bloodBankT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable bloodBankT;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
