/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myPanel;

import domain.InsertData;

/**
 *
 * @author Shadhin
 */
public class BloodRequestForm extends javax.swing.JPanel {

    /**
     * Creates new form BloodRequest
     */
    public BloodRequestForm() {
        initComponents();
        rSexMaleRB.setSelected(true);
        sex = rSexMaleRB.getText();
        rSexFemaleRB.setSelected(false);
        rSexOtherRB.setSelected(false);
        //System.out.println("Sex: "+sex);
        rBloodGCB.setSelectedIndex(0);
        bloodG = rBloodGCB.getSelectedItem().toString();
    }

    private String name;
    private String mobile;
    private String sex;
    private String bloodG;
    private String email;
    private String address;
    private String alternativeMN;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        rSubmitB = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        rAlternativeMNTF = new javax.swing.JTextField();
        rMobileNTF = new javax.swing.JTextField();
        rAddressTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        rEmailTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        rNameTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        rBloodGCB = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        rSexMaleRB = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        rSexFemaleRB = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        rSexOtherRB = new javax.swing.JRadioButton();

        setMaximumSize(new java.awt.Dimension(700, 503));
        setMinimumSize(new java.awt.Dimension(700, 503));
        setPreferredSize(new java.awt.Dimension(700, 503));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Email:");

        rSubmitB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rSubmitB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/submitButton.png"))); // NOI18N
        rSubmitB.setText("Submit");
        rSubmitB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSubmitBActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Address:");

        rAlternativeMNTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        rMobileNTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        rAddressTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Blood Request Form");

        rEmailTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Full Name:");

        rNameTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Sex:");

        rBloodGCB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rBloodGCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-" }));
        rBloodGCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBloodGCBActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Blood Group:");

        rSexMaleRB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rSexMaleRB.setText("Male");
        rSexMaleRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSexMaleRBActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Mobile Number:");

        rSexFemaleRB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rSexFemaleRB.setText("Female");
        rSexFemaleRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSexFemaleRBActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Alternative Mobile Number:");

        rSexOtherRB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rSexOtherRB.setText("Others");
        rSexOtherRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSexOtherRBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(237, 237, 237))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(rSubmitB))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(39, 39, 39))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(139, 139, 139))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(166, 166, 166))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(149, 149, 149))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(107, 107, 107))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(121, 121, 121))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(174, 174, 174)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rMobileNTF)
                                .addComponent(rAddressTF)
                                .addComponent(rEmailTF)
                                .addComponent(rAlternativeMNTF)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(rSexMaleRB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(32, 32, 32)
                                    .addComponent(rSexFemaleRB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(33, 33, 33)
                                    .addComponent(rSexOtherRB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(rNameTF)
                                .addComponent(rBloodGCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(127, 127, 127))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rSexMaleRB)
                    .addComponent(rSexFemaleRB)
                    .addComponent(rSexOtherRB))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rBloodGCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rEmailTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rAddressTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rMobileNTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rAlternativeMNTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(rSubmitB)
                .addGap(57, 57, 57))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rSubmitBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSubmitBActionPerformed
        // TODO add your handling code here:
        name = rNameTF.getText();
        mobile = rMobileNTF.getText();
        email = rEmailTF.getText();
        address = rAddressTF.getText();
        alternativeMN = rAlternativeMNTF.getText();
        
        InsertData id = new InsertData();
        id.insertRequest(mobile, name, sex, bloodG, email, address, alternativeMN);    
    }//GEN-LAST:event_rSubmitBActionPerformed

    private void rSexMaleRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSexMaleRBActionPerformed
        // TODO add your handling code here:
        if (rSexMaleRB.isSelected()) {
            rSexFemaleRB.setSelected(false);
            rSexOtherRB.setSelected(false);
            sex = rSexMaleRB.getText();
            //System.out.println("Sex: "+sex);
        }
    }//GEN-LAST:event_rSexMaleRBActionPerformed

    private void rSexFemaleRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSexFemaleRBActionPerformed
        // TODO add your handling code here:
        if (rSexFemaleRB.isSelected()) {
            rSexMaleRB.setSelected(false);
            rSexOtherRB.setSelected(false);
            sex = rSexFemaleRB.getText();
            //System.out.println("Sex: "+sex);
        }
    }//GEN-LAST:event_rSexFemaleRBActionPerformed

    private void rSexOtherRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSexOtherRBActionPerformed
        // TODO add your handling code here:
        if (rSexOtherRB.isSelected()) {
            rSexMaleRB.setSelected(false);
            rSexFemaleRB.setSelected(false);
            sex = rSexOtherRB.getText();
            //System.out.println("Sex: "+sex);
        }
    }//GEN-LAST:event_rSexOtherRBActionPerformed

    private void rBloodGCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBloodGCBActionPerformed
        // TODO add your handling code here:
        bloodG = rBloodGCB.getSelectedItem().toString();
        //System.out.println("BloodG: "+bloodG);
    }//GEN-LAST:event_rBloodGCBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField rAddressTF;
    private javax.swing.JTextField rAlternativeMNTF;
    private javax.swing.JComboBox<String> rBloodGCB;
    private javax.swing.JTextField rEmailTF;
    private javax.swing.JTextField rMobileNTF;
    private javax.swing.JTextField rNameTF;
    private javax.swing.JRadioButton rSexFemaleRB;
    private javax.swing.JRadioButton rSexMaleRB;
    private javax.swing.JRadioButton rSexOtherRB;
    private javax.swing.JButton rSubmitB;
    // End of variables declaration//GEN-END:variables
}
