/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myPanel;

import domain.DisplayData;
import domain.Donor;
import domain.Request;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Shadhin
 */
public class DonorSearch extends javax.swing.JPanel {

    /**
     * Creates new form DonorSearch
     */
    public DonorSearch() {
        initComponents();
        //showDonor();
    }
    DisplayData dd = new DisplayData();
    ArrayList<Donor> donor;
    DefaultTableModel model;
String mobile;
    public void showDonor() {
        //model.setRowCount(0);
        try {
            model.setRowCount(0);
        } catch (Exception e) {
        }
        model = (DefaultTableModel) donorSearchT.getModel();
        Object[] row = new Object[10];
        for (int i = 0; i < donor.size(); i++) {
            row[0] = donor.get(i).getDonorId();
            row[1] = donor.get(i).getdName();
            row[2] = donor.get(i).getdSex();
            row[3] = donor.get(i).getdBloodG();
            row[4] = donor.get(i).getdMobileN();
            row[5] = donor.get(i).getdEmail();
            row[6] = donor.get(i).getdAddress();
            row[7] = donor.get(i).getdAlternativeMN();
            row[8] = donor.get(i).getRegistrationDate();
            //row[9] = donor.get(i).getRegistrationDate();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dSMobileNTF = new javax.swing.JTextField();
        dSearchB = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        donorSearchT = new javax.swing.JTable();

        setMaximumSize(new java.awt.Dimension(700, 503));
        setMinimumSize(new java.awt.Dimension(700, 503));
        setPreferredSize(new java.awt.Dimension(700, 503));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Donor Search");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Mobile Number:");

        dSMobileNTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dSMobileNTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dSMobileNTFActionPerformed(evt);
            }
        });

        dSearchB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dSearchB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/searchButtonIcon.png"))); // NOI18N
        dSearchB.setText("Search");
        dSearchB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dSearchBActionPerformed(evt);
            }
        });

        donorSearchT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        donorSearchT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "Sex", "Blood Group", "Mobile Number", "Email", "Address", "Alternative Mobile Number", "Registration Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(donorSearchT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addComponent(dSMobileNTF, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99)
                        .addComponent(dSearchB))
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(dSMobileNTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dSearchB))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void dSMobileNTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dSMobileNTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dSMobileNTFActionPerformed

    private void dSearchBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dSearchBActionPerformed
        // TODO add your handling code here:
        mobile = dSMobileNTF.getText();
        donor = dd.getDonor(mobile);
        //model.setRowCount(0);
        if(donor.isEmpty()){
            model.setRowCount(0);
           JOptionPane.showMessageDialog(null, "Sorry! Not a registered donor");
        }else{
            showDonor();
        }
        
    }//GEN-LAST:event_dSearchBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dSMobileNTF;
    private javax.swing.JButton dSearchB;
    private javax.swing.JTable donorSearchT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
