/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myPanel;

import domain.InsertData;

/**
 *
 * @author Shadhin
 */
public class DonorRegistrationForm extends javax.swing.JPanel {

    /**
     * Creates new form DonorRegistrationForm
     */
    private String name;
    private String mobile;
    private String sex;
    private String bloodG;
    private String email;
    private String address;
    private String alternativeMN;

    public DonorRegistrationForm() {
        initComponents();
        dSexMaleRB.setSelected(true);
        sex = dSexMaleRB.getText();
        dSexFemaleRB.setSelected(false);
        dSexOtherRB.setSelected(false);
        //System.out.println("Sex: " + sex);
        dBloodGCB.setSelectedIndex(0);
        bloodG = dBloodGCB.getSelectedItem().toString();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        dAlternativeMNTF = new javax.swing.JTextField();
        dMobileNTF = new javax.swing.JTextField();
        dAddressTF = new javax.swing.JTextField();
        dEmailTF = new javax.swing.JTextField();
        dNameTF = new javax.swing.JTextField();
        dBloodGCB = new javax.swing.JComboBox<>();
        dSexMaleRB = new javax.swing.JRadioButton();
        dSexFemaleRB = new javax.swing.JRadioButton();
        dSexOtherRB = new javax.swing.JRadioButton();
        dSubmitB = new javax.swing.JButton();

        setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        setMaximumSize(new java.awt.Dimension(700, 503));
        setMinimumSize(new java.awt.Dimension(700, 503));
        setPreferredSize(new java.awt.Dimension(700, 503));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Donor Registration Form");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Full Name:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Sex:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Blood Group:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Mobile Number:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Alternative Mobile Number:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Email:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Address:");

        dAlternativeMNTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        dMobileNTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        dAddressTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        dEmailTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        dNameTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        dBloodGCB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dBloodGCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-" }));
        dBloodGCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dBloodGCBActionPerformed(evt);
            }
        });

        dSexMaleRB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dSexMaleRB.setText("Male");
        dSexMaleRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dSexMaleRBActionPerformed(evt);
            }
        });

        dSexFemaleRB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dSexFemaleRB.setText("Female");
        dSexFemaleRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dSexFemaleRBActionPerformed(evt);
            }
        });

        dSexOtherRB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dSexOtherRB.setText("Others");
        dSexOtherRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dSexOtherRBActionPerformed(evt);
            }
        });

        dSubmitB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dSubmitB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/submitButton.png"))); // NOI18N
        dSubmitB.setText("Submit");
        dSubmitB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dSubmitBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(191, 191, 191))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(dSubmitB))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(39, 39, 39))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(139, 139, 139))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(166, 166, 166))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(149, 149, 149))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(107, 107, 107))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(121, 121, 121))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(174, 174, 174)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(dMobileNTF)
                                .addComponent(dAddressTF)
                                .addComponent(dEmailTF)
                                .addComponent(dAlternativeMNTF)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(dSexMaleRB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(32, 32, 32)
                                    .addComponent(dSexFemaleRB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(33, 33, 33)
                                    .addComponent(dSexOtherRB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(dNameTF)
                                .addComponent(dBloodGCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(133, 133, 133))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dSexMaleRB)
                    .addComponent(dSexFemaleRB)
                    .addComponent(dSexOtherRB))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dBloodGCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dEmailTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dAddressTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dMobileNTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dAlternativeMNTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(dSubmitB)
                .addGap(90, 90, 90))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void dSubmitBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dSubmitBActionPerformed
        // TODO add your handling code here:
        name = dNameTF.getText();
        mobile = dMobileNTF.getText();
        email = dEmailTF.getText();
        address = dAddressTF.getText();
        alternativeMN = dAlternativeMNTF.getText();
        
        InsertData id = new InsertData();
        id.insertDonor(mobile, name, sex, bloodG, email, address, alternativeMN); 
        //id.insertDonation(mobile, bloodG);
    }//GEN-LAST:event_dSubmitBActionPerformed

    private void dSexMaleRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dSexMaleRBActionPerformed
        // TODO add your handling code here:
        if (dSexMaleRB.isSelected()) {
            dSexFemaleRB.setSelected(false);
            dSexOtherRB.setSelected(false);
            sex = dSexMaleRB.getText();
            //System.out.println("Sex: " + sex);
        }
    }//GEN-LAST:event_dSexMaleRBActionPerformed

    private void dSexFemaleRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dSexFemaleRBActionPerformed
        // TODO add your handling code here:
        if (dSexFemaleRB.isSelected()) {
            dSexMaleRB.setSelected(false);
            dSexOtherRB.setSelected(false);
            sex = dSexFemaleRB.getText();
            //System.out.println("Sex: " + sex);
        }
    }//GEN-LAST:event_dSexFemaleRBActionPerformed

    private void dSexOtherRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dSexOtherRBActionPerformed
        // TODO add your handling code here:
        if (dSexOtherRB.isSelected()) {
            dSexMaleRB.setSelected(false);
            dSexFemaleRB.setSelected(false);
            sex = dSexOtherRB.getText();
            //System.out.println("Sex: " + sex);
        }

    }//GEN-LAST:event_dSexOtherRBActionPerformed

    private void dBloodGCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dBloodGCBActionPerformed
        // TODO add your handling code here:
        bloodG = dBloodGCB.getSelectedItem().toString();
        //System.out.println("BloodG: " + bloodG);
    }//GEN-LAST:event_dBloodGCBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dAddressTF;
    private javax.swing.JTextField dAlternativeMNTF;
    private javax.swing.JComboBox<String> dBloodGCB;
    private javax.swing.JTextField dEmailTF;
    private javax.swing.JTextField dMobileNTF;
    private javax.swing.JTextField dNameTF;
    private javax.swing.JRadioButton dSexFemaleRB;
    private javax.swing.JRadioButton dSexMaleRB;
    private javax.swing.JRadioButton dSexOtherRB;
    private javax.swing.JButton dSubmitB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
