/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myPanel;

import domain.InsertData;
import javax.swing.JOptionPane;

/**
 *
 * @author Shadhin
 */
public class OperatorRegistrationForm extends javax.swing.JPanel {

    /**
     * Creates new form OperatorRegistrationForm
     */
    public OperatorRegistrationForm() {
        initComponents();
        oSexMaleRB.setSelected(true);
        sex = oSexMaleRB.getText();
        oSexFemaleRB.setSelected(false);
        oSexOtherRB.setSelected(false);
        oBloodGCB.setSelectedIndex(0);
        bloodG = oBloodGCB.getSelectedItem().toString();
    }

    String email;
    String password;
    String rePassword;
    private String name;
    private String mobile;
    private String sex;
    private String bloodG;
    private String address;
    private String alternativeMN;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        oSubmitB = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        oAlternativeMNTF = new javax.swing.JTextField();
        oMobileNTF = new javax.swing.JTextField();
        oAddressTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        oEmailTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        oNameTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        oBloodGCB = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        oSexMaleRB = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        oSexFemaleRB = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        oSexOtherRB = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        oPasswordPF = new javax.swing.JPasswordField();
        oRePasswordPF = new javax.swing.JPasswordField();

        setMaximumSize(new java.awt.Dimension(700, 503));
        setMinimumSize(new java.awt.Dimension(700, 503));
        setPreferredSize(new java.awt.Dimension(700, 503));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Email:");

        oSubmitB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        oSubmitB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/submitButton.png"))); // NOI18N
        oSubmitB.setText("Submit");
        oSubmitB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oSubmitBActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Address:");

        oAlternativeMNTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        oMobileNTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        oAddressTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Operator Registration Form");

        oEmailTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Full Name:");

        oNameTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Sex:");

        oBloodGCB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        oBloodGCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-" }));
        oBloodGCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oBloodGCBActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Blood Group:");

        oSexMaleRB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        oSexMaleRB.setText("Male");
        oSexMaleRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oSexMaleRBActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Mobile Number:");

        oSexFemaleRB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        oSexFemaleRB.setText("Female");
        oSexFemaleRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oSexFemaleRBActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Alternative Mobile Number:");

        oSexOtherRB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        oSexOtherRB.setText("Others");
        oSexOtherRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oSexOtherRBActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Password:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Retype Password:");

        oPasswordPF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        oRePasswordPF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(191, 191, 191))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(oSubmitB))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(39, 39, 39))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(139, 139, 139))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(149, 149, 149))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(107, 107, 107))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(121, 121, 121))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(174, 174, 174))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(25, 25, 25))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(10, 10, 10))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(oEmailTF)
                                .addComponent(oMobileNTF)
                                .addComponent(oAddressTF)
                                .addComponent(oAlternativeMNTF)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(oSexMaleRB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(32, 32, 32)
                                    .addComponent(oSexFemaleRB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(33, 33, 33)
                                    .addComponent(oSexOtherRB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(oNameTF)
                                .addComponent(oRePasswordPF)
                                .addComponent(oBloodGCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(oPasswordPF)))))
                .addGap(113, 113, 113))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(oEmailTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(oPasswordPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(oRePasswordPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(oNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(oSexMaleRB)
                    .addComponent(oSexFemaleRB)
                    .addComponent(oSexOtherRB))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(oBloodGCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(oAddressTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(oMobileNTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(oAlternativeMNTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(oSubmitB)
                .addGap(40, 40, 40))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void oSubmitBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oSubmitBActionPerformed
        // TODO add your handling code here:
        email = oEmailTF.getText();
        password = oPasswordPF.getText().toString();
        rePassword = oRePasswordPF.getText().toString();
        name = oNameTF.getText();
        mobile = oMobileNTF.getText();
        address = oAddressTF.getText();
        alternativeMN = oAlternativeMNTF.getText();
        System.out.println("Password: "+password);
        System.out.println("RePassword: "+rePassword);
        if (password.equals(rePassword)) {
            InsertData id = new InsertData();
            id.insertOperator(mobile, name, sex, bloodG, email, address, alternativeMN, password);
        } else {
            JOptionPane.showMessageDialog(null, "Please Check Password");
        }

    }//GEN-LAST:event_oSubmitBActionPerformed

    private void oSexMaleRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oSexMaleRBActionPerformed
        // TODO add your handling code here:
        if (oSexMaleRB.isSelected()) {
            oSexMaleRB.setSelected(true);
            sex = oSexMaleRB.getText();
            oSexFemaleRB.setSelected(false);
            oSexOtherRB.setSelected(false);
        }
    }//GEN-LAST:event_oSexMaleRBActionPerformed

    private void oSexFemaleRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oSexFemaleRBActionPerformed
        // TODO add your handling code here:
        if (oSexFemaleRB.isSelected()) {
            oSexMaleRB.setSelected(false);
            oSexFemaleRB.setSelected(true);
            sex = oSexFemaleRB.getText();
            oSexOtherRB.setSelected(false);
        }
    }//GEN-LAST:event_oSexFemaleRBActionPerformed

    private void oSexOtherRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oSexOtherRBActionPerformed
        // TODO add your handling code here:
        if (oSexOtherRB.isSelected()) {
            oSexMaleRB.setSelected(false);
            oSexFemaleRB.setSelected(false);
            oSexOtherRB.setSelected(true);
            sex = oSexOtherRB.getText();
        }
    }//GEN-LAST:event_oSexOtherRBActionPerformed

    private void oBloodGCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oBloodGCBActionPerformed
        // TODO add your handling code here:
        bloodG = oBloodGCB.getSelectedItem().toString();
    }//GEN-LAST:event_oBloodGCBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField oAddressTF;
    private javax.swing.JTextField oAlternativeMNTF;
    private javax.swing.JComboBox<String> oBloodGCB;
    private javax.swing.JTextField oEmailTF;
    private javax.swing.JTextField oMobileNTF;
    private javax.swing.JTextField oNameTF;
    private javax.swing.JPasswordField oPasswordPF;
    private javax.swing.JPasswordField oRePasswordPF;
    private javax.swing.JRadioButton oSexFemaleRB;
    private javax.swing.JRadioButton oSexMaleRB;
    private javax.swing.JRadioButton oSexOtherRB;
    private javax.swing.JButton oSubmitB;
    // End of variables declaration//GEN-END:variables
}
