/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import domain.DisplayData;
import domain.Donation;
import myPanel.About;
import myPanel.BloodBank;
import myPanel.BloodSearch;
import myPanel.DonateBlood;
import myPanel.DonorRegistrationForm;
import myPanel.DonorSearch;
import myPanel.OperatorRegistrationForm;
import myPanel.OperatorRequestApproval;
import myPanel.BloodRequestApproval;
import myPanel.BloodRequestForm;
import myPanel.RequestSearch;
import myPanel.SellReport;
import myPanel.SignIn;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Shadhin
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    GridBagLayout layout = new GridBagLayout();
    //SignIn si;
    About a;
    DonorRegistrationForm drf;
    OperatorRegistrationForm orf;
    DonateBlood db;
    DonorSearch ds;
    RequestSearch rs;
    BloodSearch bs;
    BloodBank bb;
    OperatorRequestApproval ora;
    SellReport s;
    BloodRequestApproval bra;
    BloodRequestForm brf;

    private int access = 0;

    public MainFrame(int access) {
        super("Blood Bank Management System");
        initComponents();

        this.access = access;
        a = new About();
        mainPanel.setLayout(layout);
        GridBagConstraints c = new GridBagConstraints();
        c.gridx = 0;
        c.gridy = 0;
        mainPanel.add(a, c);
        a.setVisible(true);
        drf = new DonorRegistrationForm();
        mainPanel.add(drf, c);
        drf.setVisible(false);
        db = new DonateBlood();
        mainPanel.add(db, c);
        db.setVisible(false);
        ds = new DonorSearch();
        mainPanel.add(ds, c);
        ds.setVisible(false);
        rs = new RequestSearch();
        mainPanel.add(rs, c);
        rs.setVisible(false);
        bs = new BloodSearch();
        mainPanel.add(bs, c);
        bs.setVisible(false);

        orf = new OperatorRegistrationForm();
        mainPanel.add(orf, c);
        orf.setVisible(false);

        bb = new BloodBank();
        mainPanel.add(bb, c);
        bb.setVisible(false);

        ora = new OperatorRequestApproval();
        mainPanel.add(ora, c);
        ora.setVisible(false);

        bra = new BloodRequestApproval();
        mainPanel.add(bra, c);
        bra.setVisible(false);

        s = new SellReport();
        mainPanel.add(s, c);
        s.setVisible(false);

        //a = new About();
        //mainPanel.add(a, c);
        //a.setVisible(false);
        brf = new BloodRequestForm();
        mainPanel.add(brf, c);
        brf.setVisible(false);
        setIconImage(new ImageIcon(getClass().getResource("/icon/mainIcon.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        fileM = new javax.swing.JMenu();
        aboutMI = new javax.swing.JMenuItem();
        exitMI = new javax.swing.JMenuItem();
        registrationM = new javax.swing.JMenu();
        donorRegMI = new javax.swing.JMenuItem();
        operatorRegMI = new javax.swing.JMenuItem();
        requestM = new javax.swing.JMenu();
        bloodReqMI = new javax.swing.JMenuItem();
        donateBloodMI = new javax.swing.JMenuItem();
        searchM = new javax.swing.JMenu();
        donorSearchMI = new javax.swing.JMenuItem();
        bloodSearchMI = new javax.swing.JMenuItem();
        requestSearchMI = new javax.swing.JMenuItem();
        adminM = new javax.swing.JMenu();
        bloodBMI = new javax.swing.JMenuItem();
        operatorReqMI = new javax.swing.JMenuItem();
        reqApprovalMI = new javax.swing.JMenuItem();
        sellMI = new javax.swing.JMenuItem();
        closeM = new javax.swing.JMenu();
        closeMI = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 482, Short.MAX_VALUE)
        );

        fileM.setText("File");

        aboutMI.setText("About");
        aboutMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMIActionPerformed(evt);
            }
        });
        fileM.add(aboutMI);

        exitMI.setText("Exit");
        exitMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMIActionPerformed(evt);
            }
        });
        fileM.add(exitMI);

        menuBar.add(fileM);

        registrationM.setText("Registration");

        donorRegMI.setText("Donor");
        donorRegMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donorRegMIActionPerformed(evt);
            }
        });
        registrationM.add(donorRegMI);

        operatorRegMI.setText("Operator");
        operatorRegMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operatorRegMIActionPerformed(evt);
            }
        });
        registrationM.add(operatorRegMI);

        menuBar.add(registrationM);

        requestM.setText("Request");

        bloodReqMI.setText("Blood Request");
        bloodReqMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloodReqMIActionPerformed(evt);
            }
        });
        requestM.add(bloodReqMI);

        donateBloodMI.setText("Donate Blood");
        donateBloodMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donateBloodMIActionPerformed(evt);
            }
        });
        requestM.add(donateBloodMI);

        menuBar.add(requestM);

        searchM.setText("Search");

        donorSearchMI.setText("Donor");
        donorSearchMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donorSearchMIActionPerformed(evt);
            }
        });
        searchM.add(donorSearchMI);

        bloodSearchMI.setText("Blood");
        bloodSearchMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloodSearchMIActionPerformed(evt);
            }
        });
        searchM.add(bloodSearchMI);

        requestSearchMI.setText("Request");
        requestSearchMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestSearchMIActionPerformed(evt);
            }
        });
        searchM.add(requestSearchMI);

        menuBar.add(searchM);

        adminM.setText("Admin");

        bloodBMI.setText("Blood Bank");
        bloodBMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloodBMIActionPerformed(evt);
            }
        });
        adminM.add(bloodBMI);

        operatorReqMI.setText("Operator Request");
        operatorReqMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operatorReqMIActionPerformed(evt);
            }
        });
        adminM.add(operatorReqMI);

        reqApprovalMI.setText("Blood Request");
        reqApprovalMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reqApprovalMIActionPerformed(evt);
            }
        });
        adminM.add(reqApprovalMI);

        sellMI.setText("Sell");
        sellMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellMIActionPerformed(evt);
            }
        });
        adminM.add(sellMI);

        menuBar.add(adminM);

        closeM.setText("Close");
        closeM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeMActionPerformed(evt);
            }
        });

        closeMI.setText("Close");
        closeMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeMIActionPerformed(evt);
            }
        });
        closeM.add(closeMI);

        menuBar.add(closeM);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMIActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitMIActionPerformed

    private void donorRegMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donorRegMIActionPerformed
        // TODO add your handling code here:
        //si.setVisible(false);
        drf.setVisible(true);
        db.setVisible(false);
        ds.setVisible(false);
        rs.setVisible(false);
        bs.setVisible(false);
        orf.setVisible(false);
        bb.setVisible(false);
        bra.setVisible(false);
        ora.setVisible(false);
        s.setVisible(false);
        a.setVisible(false);
        brf.setVisible(false);
    }//GEN-LAST:event_donorRegMIActionPerformed

    private void closeMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_closeMActionPerformed

    private void closeMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeMIActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeMIActionPerformed

    private void donateBloodMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donateBloodMIActionPerformed
        // TODO add your handling code here:
        //si.setVisible(false);
        drf.setVisible(false);
        db.setVisible(true);
        ds.setVisible(false);
        rs.setVisible(false);
        bs.setVisible(false);
        orf.setVisible(false);
        bb.setVisible(false);
        bra.setVisible(false);
        ora.setVisible(false);
        s.setVisible(false);
        a.setVisible(false);
        brf.setVisible(false);
    }//GEN-LAST:event_donateBloodMIActionPerformed

    private void donorSearchMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donorSearchMIActionPerformed
        // TODO add your handling code here:
        //si.setVisible(false);
        drf.setVisible(false);
        db.setVisible(false);
        ds.setVisible(true);
        rs.setVisible(false);
        bs.setVisible(false);
        orf.setVisible(false);
        bb.setVisible(false);
        bra.setVisible(false);
        ora.setVisible(false);
        s.setVisible(false);
        a.setVisible(false);
        brf.setVisible(false);
    }//GEN-LAST:event_donorSearchMIActionPerformed

    private void bloodSearchMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloodSearchMIActionPerformed
        // TODO add your handling code here:
        //si.setVisible(false);
        drf.setVisible(false);
        db.setVisible(false);
        ds.setVisible(false);
        rs.setVisible(false);
        bs.setVisible(true);
        orf.setVisible(false);
        bb.setVisible(false);
        bra.setVisible(false);
        ora.setVisible(false);
        s.setVisible(false);
        a.setVisible(false);
        brf.setVisible(false);
    }//GEN-LAST:event_bloodSearchMIActionPerformed

    private void requestSearchMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestSearchMIActionPerformed
        // TODO add your handling code here:
        //si.setVisible(false);
        drf.setVisible(false);
        db.setVisible(false);
        ds.setVisible(false);
        rs.setVisible(true);
        bs.setVisible(false);
        orf.setVisible(false);
        bb.setVisible(false);
        bra.setVisible(false);
        ora.setVisible(false);
        s.setVisible(false);
        a.setVisible(false);
        brf.setVisible(false);
    }//GEN-LAST:event_requestSearchMIActionPerformed

    private void operatorRegMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_operatorRegMIActionPerformed
        // TODO add your handling code here:
        //si.setVisible(false);
        drf.setVisible(false);
        db.setVisible(false);
        ds.setVisible(false);
        rs.setVisible(false);
        bs.setVisible(false);
        orf.setVisible(true);
        bb.setVisible(false);
        bra.setVisible(false);
        ora.setVisible(false);
        s.setVisible(false);
        a.setVisible(false);
        brf.setVisible(false);
    }//GEN-LAST:event_operatorRegMIActionPerformed

    private void aboutMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMIActionPerformed
        // TODO add your handling code here:
        //si.setVisible(false);
        drf.setVisible(false);
        db.setVisible(false);
        ds.setVisible(false);
        rs.setVisible(false);
        bs.setVisible(false);
        orf.setVisible(false);
        bb.setVisible(false);
        bra.setVisible(false);
        ora.setVisible(false);
        s.setVisible(false);
        a.setVisible(true);
        brf.setVisible(false);
    }//GEN-LAST:event_aboutMIActionPerformed

    private void bloodReqMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloodReqMIActionPerformed
        // TODO add your handling code here:
        //si.setVisible(false);
        drf.setVisible(false);
        db.setVisible(false);
        ds.setVisible(false);
        rs.setVisible(false);
        bs.setVisible(false);
        orf.setVisible(false);
        bb.setVisible(false);
        bra.setVisible(false);
        ora.setVisible(false);
        s.setVisible(false);
        a.setVisible(false);
        brf.setVisible(true);
    }//GEN-LAST:event_bloodReqMIActionPerformed

    private void bloodBMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloodBMIActionPerformed
        // TODO add your handling code here:
        //si.setVisible(false);
        drf.setVisible(false);
        db.setVisible(false);
        ds.setVisible(false);
        rs.setVisible(false);
        bs.setVisible(false);
        orf.setVisible(false);
        bb.setVisible(true);
        bra.setVisible(false);
        ora.setVisible(false);
        s.setVisible(false);
        a.setVisible(false);
        brf.setVisible(false);

        bb.showDonor();
    }//GEN-LAST:event_bloodBMIActionPerformed

    private void operatorReqMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_operatorReqMIActionPerformed
        // TODO add your handling code here:
        //si.setVisible(false);

        if (access == 2) {
            drf.setVisible(false);
            db.setVisible(false);
            ds.setVisible(false);
            rs.setVisible(false);
            bs.setVisible(false);
            orf.setVisible(false);
            bb.setVisible(false);
            bra.setVisible(false);
            s.setVisible(false);
            a.setVisible(false);
            brf.setVisible(false);
            ora.setVisible(true);
            ora.showOperatorRequest();
        }


    }//GEN-LAST:event_operatorReqMIActionPerformed

    private void reqApprovalMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reqApprovalMIActionPerformed
        // TODO add your handling code here:
        //si.setVisible(false);
        drf.setVisible(false);
        db.setVisible(false);
        ds.setVisible(false);
        rs.setVisible(false);
        bs.setVisible(false);
        orf.setVisible(false);
        bb.setVisible(false);
        bra.setVisible(true);
        ora.setVisible(false);
        s.setVisible(false);
        a.setVisible(false);
        brf.setVisible(false);
        bra.showRequestTable();
    }//GEN-LAST:event_reqApprovalMIActionPerformed

    private void sellMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellMIActionPerformed
        // TODO add your handling code here:
        //si.setVisible(false);
        drf.setVisible(false);
        db.setVisible(false);
        ds.setVisible(false);
        rs.setVisible(false);
        bs.setVisible(false);
        orf.setVisible(false);
        bb.setVisible(false);
        bra.setVisible(false);
        ora.setVisible(false);
        s.setVisible(true);
        a.setVisible(false);
        brf.setVisible(false);
        s.showSellData();
    }//GEN-LAST:event_sellMIActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame(1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMI;
    private javax.swing.JMenu adminM;
    private javax.swing.JMenuItem bloodBMI;
    private javax.swing.JMenuItem bloodReqMI;
    private javax.swing.JMenuItem bloodSearchMI;
    private javax.swing.JMenu closeM;
    private javax.swing.JMenuItem closeMI;
    private javax.swing.JMenuItem donateBloodMI;
    private javax.swing.JMenuItem donorRegMI;
    private javax.swing.JMenuItem donorSearchMI;
    private javax.swing.JMenuItem exitMI;
    private javax.swing.JMenu fileM;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem operatorRegMI;
    private javax.swing.JMenuItem operatorReqMI;
    private javax.swing.JMenu registrationM;
    private javax.swing.JMenuItem reqApprovalMI;
    private javax.swing.JMenu requestM;
    private javax.swing.JMenuItem requestSearchMI;
    private javax.swing.JMenu searchM;
    private javax.swing.JMenuItem sellMI;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the access
     */
    public int getAccess() {
        return access;
    }

    /**
     * @param access the access to set
     */
    public void setAccess(int access) {
        this.access = access;
    }
}
